from dash import html
import dash_bootstrap_components as dbc

# About Section
def get_about_section():
    return dbc.Container(
        [
            html.H3("About This Dashboard", className="text-primary"),
            html.P([
                "This dashboard is designed for analyzing the summary excel file generated by the ",
                html.A("assembly workflow", href="https://github.com/bacterial-genomics/wf-paired-end-illumina-assembly", target="_blank", className="text-primary fw-bold"),
                " data. It supports Kraken2 TSV outputs and Summary Excel file, allowing users to visualize Sankey plots and bar plots for assembly depth."
            ]),
            html.P("""
                By uploading a dataset, users can explore and visualize their assembly workflow metrics, classifications, assess sequencing depth,
                and gain insights into their sequencing data in a user-friendly interface.
            """),
            html.H4("Features:", className="text-secondary"),
            html.Ul([
                html.Li("🔹 Upload Kraken report TSV or Summary Excel file"),
                html.Li("🔹 Visualize taxonomic classifications using Sankey diagrams"),
                html.Li("🔹 Generate stacked bar plots for coverage depth"),
                html.Li("🔹 Select individual sheets and samples for analysis"),
            ]),
            html.P("This tool is developed to assist bioinformaticians in taxonomic and assembly depth analysis."),
            html.P([
                "This application was created and maintained by Taylor K. Paisie. Check out my ",
                html.A("website", href="https://taylorpaisie.github.io/", target="_blank", className="text-primary fw-bold"),
                " or my ",
                html.A("Github Repositories", href="https://github.com/taylorpaisie", target="_blank", className="text-primary fw-bold"),
                "."
            ]),
            html.P(["If you have any questions or issues about the Assembly Workflow Dashboard, please submit an issue on the ",
                html.A("Assembly Workflow Github Repository", href="https://github.com/taylorpaisie/assembly_wf_dashboard", target="_blank", className="text-primary fw-bold"),
                "."
            ])            
        ],
        style={'padding': '20px'}
    )

# How to Use Section
def get_how_to_use_section():
    return dbc.Container(
        [
            html.H3("How to Use", className="text-primary"),
            html.P("""
                Follow these steps to analyze your data with the dashboard:
            """),
            html.Ol([
                html.Li("Click on 'Upload' to select a Kraken2 TSV or Excel file."),
                html.Li("Choose the correct sheet from the dropdown."),
                html.Li("Use the available controls to filter and analyze the data."),
                html.Li("View taxonomic classification in a Sankey diagram."),
                html.Li("Check assembly depth using the bar plot."),
            ]),
            html.H4("📌 Tips:", className="text-secondary"),
            html.Ul([
                html.Li("Ensure your file format matches the expected input."),
                html.Li("If using Kraken2 data, confirm that it includes taxonomic rank information."),
                html.Li("For large datasets, expect a short processing time."),
            ]),
            html.P("By following these steps, you can easily explore your dataset."),

            html.Figure([
                html.Img(
                    src='/assets/hiding_ham.jpg',  # Path to the image
                    alt='Hiding Hamilton',
                    style={'width': '25%', 'height': 'auto', 'marginTop': '20px'}
                ),
                html.Figcaption(
                    "Don't be like Hamilton and hide from your data!",
                    style={'textAlign': 'left', 'fontStyle': 'italic', 'marginTop': '10px'}
                )
            ])

        ],
        style={'padding': '20px'}
    )
